name: Host - update, upgrade and install qemu-user-static binfmt-support
description: Download all artifacts from the latest release
inputs:
  distinct_id:
    description: "Distinct ID for the artifacts"
    required: true
runs:
  using: "composite"
  steps:
    - name: Are we in a container? ${{ inputs.distinct_id }}
      shell: bash
      run: |

        awk -F/ '/docker/ {print $2}' /proc/self/cgroup

        exit 1

        if awk -F/ '/docker/ {print $2}' /proc/self/cgroup | grep -q docker; then
            printf '%s\n' "Running inside a Docker container"
            printf '%s\n' "we_are_in_docker=yes" >> $GITHUB_ENV
        fi

    - name: Host - phased updates ${{ inputs.distinct_id }}
      if: env.we_are_in_docker != 'yes'
      shell: bash
      run: printf '%s\n' 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates

    - name: Host - update ${{ inputs.distinct_id }}
      shell: bash
      run: |
        if [[ ${{ env.we_are_in_docker }} == 'yes' ]]; then
            apt-get update
        else
            sudo apt-get update
        fi

    - name: Host - upgrade ${{ inputs.distinct_id }}
      shell: bash
      run: |
        if [[ ${{ env.we_are_in_docker }} == 'yes' ]]; then
            apt-get -y upgrade
        else
            sudo apt-get -y upgrade
        fi

    - name: Host - set up qemu-user-static binfmt-support ${{ inputs.distinct_id }}
      if: env.we_are_in_docker != 'yes'
      shell: bash
      run: sudo apt install libpipeline1 qemu-user-static binfmt-support
