name: ci-checks
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sh-checker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS: -e SC2034,SC1091 # It is possible to exclude some shellcheck warnings.
          SHFMT_OPTS: -ci -sr -i 0 # It is possible to pass arguments to shftm
        with:
          sh_checker_comment: true
          sh_checker_exclude: ""

  zizmor-workflow-audits:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: zizmor workflow audits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install zizmor

          printf '%b\n' "\`\`\`" >> $GITHUB_STEP_SUMMARY
          zizmor . --gh-token $GITHUB_TOKEN >> $GITHUB_STEP_SUMMARY
          printf '%b' "\`\`\`" >> $GITHUB_STEP_SUMMARY

  editorconfig-checker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: editorconfig-checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -Lo- "https://github.com/editorconfig-checker/editorconfig-checker/releases/latest/download/ec-linux-amd64.tar.gz" | tar xzf - --strip-components=1
          curl -LO "https://raw.githubusercontent.com/buildkite/terminal-to-html/refs/heads/main/internal/assets/terminal.css"
          tth_version=$(curl -fsSLI -o /dev/null -w %{url_effective} https://github.com/buildkite/terminal-to-html/releases/latest | xargs basename)
          curl -Lo- "https://github.com/buildkite/terminal-to-html/releases/latest/download/terminal-to-html-${tth_version/v}-linux-amd64.gz" | gunzip > tth

          chmod +x ec-linux-amd64 tth
          ./ec-linux-amd64 --exclude '^(docs/.*|patches/.*)$' | ./tth > summary-1.html

          cat > summary-2.html <<-TEST
          <!DOCTYPE html>
          <html>
          <head>
          <link rel="stylesheet" type="text/css" href="https://rawcdn.githack.com/buildkite/terminal-to-html/refs/heads/main/internal/assets/terminal.css">
          </head>
          <body>
          <div class="term-container">
          $(cat summary-1.html)
          </div>
          </body>
          </html>
          TEST

          printf '%b\n' "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat summary-2.html >> $GITHUB_STEP_SUMMARY
          printf '%b' "\`\`\`" >> $GITHUB_STEP_SUMMARY



