# @credits https://github.com/c0re100/qBittorrent-Enhanced-Edition
name: matrix multi build and release - customs tags

on:
  workflow_dispatch:
    inputs:
      distinct_id:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os_id: [alpine]
        os_version_id: [edge]
        arch_type: [x86_64, armhf, armv7, aarch64]
        libtorrent_version: ["1.2", "2.0"]
        build_tool: ["", cmake]
        qbittorrent_tag: ["-qt master"]
        include:
          - build_tool: ""
            qbt_qt_version_name: "qt5-"
            qbt_qt_version: "5"

          - build_tool: "cmake"
            qbt_qt_version_name: ""
            qbt_qt_version: "6"

          - libtorrent_version: "2.0"
            libtorrent_tag: -lt RC_2_0

          - libtorrent_version: "1.2"
            libtorrent_tag: -lt RC_1_2

    name: "${{ matrix.arch_type }}-${{ matrix.qbt_qt_version_name }}libtorrent-v${{ matrix.libtorrent_version }}"

    env:
      build_dir: "qbt-build"

    steps:
      - name: Checkout ${{ github.event.inputs.distinct_id }}
        uses: actions/checkout@v3

      - name: Host - phased updates ${{ github.event.inputs.distinct_id }}
        run: echo 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates

      - name: Host - update ${{ github.event.inputs.distinct_id }}
        run: sudo apt-get update

      - name: Host - upgrade ${{ github.event.inputs.distinct_id }}
        run: sudo apt-get -y upgrade

      - name: Host - Install host qemu-static ${{ github.event.inputs.distinct_id }}
        run: sudo apt-get install -y qemu binfmt-support qemu-user-static

      - name: Host - Docker multiarch bootstrap ${{ github.event.inputs.distinct_id }}
        run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Host - Create Docker template env file ${{ github.event.inputs.distinct_id }}
        run: |
          echo "qbt_libtorrent_version=${{ matrix.libtorrent_version }}" > env.custom
          echo "qbt_qt_version=${{ matrix.qbt_qt_version }}" >> env.custom
          echo "qbt_build_tool=${{ matrix.build_tool }}" >> env.custom
          echo "qbt_cross_name=${{ matrix.arch_type }}" >> env.custom
          echo "qbt_patches_url=${{ github.repository }}" >> env.custom
          echo "qbt_workflow_files=yes" >> env.custom
          echo "qbt_workflow_artifacts=no" >> env.custom
          echo "qbt_libtorrent_master_jamfile=no" >> env.custom
          echo "qbt_optimise_strip=yes" >> env.custom
          echo "qbt_build_debug=no" >> env.custom

      - name: Host - Create docker multiarch container ${{ github.event.inputs.distinct_id }}
        run: docker run --name multiarch -it -d --env-file env.custom -w /root -v ${{ github.workspace }}:/root ${{ matrix.os_id }}:${{ matrix.os_version_id }}

      - name: Docker - apk update ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch apk update

      - name: Docker - apk install bash ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch apk add bash

      - name: Docker - Bootstrap ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh -bs-a

      - name: Release - qt${{ matrix.qbt_qt_version }} info ${{ github.event.inputs.distinct_id }}
        run: |
          docker exec -w /root/${{ env.build_dir }}/release_info multiarch mv dependency-version.json qt${{ matrix.qbt_qt_version }}-dependency-version.json
          docker exec -w /root/${{ env.build_dir }}/release_info multiarch mv release.md qt${{ matrix.qbt_qt_version }}-release.md

      - name: Docker - zlib-ng ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh zlib

      - name: Docker - iconv ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh iconv

      - name: Docker - icu ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh icu

      - name: Docker - openssl ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh openssl

      - name: Docker - boost ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh boost

      - name: Docker - libtorrent ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh ${{ matrix.libtorrent_tag }} libtorrent

      - name: Docker - double_conversion ${{ github.event.inputs.distinct_id }}
        if: matrix.build_tool == 'cmake'
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh double_conversion

      - name: Docker - qtbase -i ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh qtbase -i

      - name: Docker - qttools ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh qttools

      - name: Docker - qbittorrent ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh ${{ matrix.qbittorrent_tag }} qbittorrent

      - name: Docker - Set release asset name ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root/${{ env.build_dir }}/completed multiarch mv -f qbittorrent-nox ${{ matrix.arch_type }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox

      - name: Docker - Release Info ${{ github.event.inputs.distinct_id }}
        run: docker exec -w /root/${{ env.build_dir }}/release_info multiarch bash -c 'mv *.md *.json '/root/${{ env.build_dir }}/completed''

      - name: Host - Upload libtorrent-v${{ matrix.libtorrent_version }}-qbittorrent-nox and release info artifact ${{ github.event.inputs.distinct_id }}
        uses: actions/upload-artifact@v3
        with:
          name: libtorrent-v${{ matrix.libtorrent_version }}-${{ matrix.arch_type }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox
          path: |
            ${{ env.build_dir }}/completed/*
            !${{ env.build_dir }}/completed/*.png

      - name: Host - Upload cmake graphs artifact ${{ github.event.inputs.distinct_id }}
        if: matrix.build_tool == 'cmake'
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.arch_type }}-libtorrent-v${{ matrix.libtorrent_version }}-graphs"
          path: "${{ env.build_dir }}/completed/*.png"

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    if: always() && contains(needs.*.result, 'success') && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    strategy:
      fail-fast: false
      matrix:
        libtorrent_version: ["1.2", "2.0"]
        include:
          - libtorrent_version: "2.0"
            preview_release: false

          - libtorrent_version: "1.2"
            preview_release: true

    name: "Publish release libtorrent-v${{ matrix.libtorrent_version }}"

    env:
      build_dir: "qbt-build"

    steps:
      - name: Checkout ${{ github.event.inputs.distinct_id }}
        uses: actions/checkout@v3

      - name: Pandoc - Bootstrap
        run: |
          pandoc_git_tag="$(git ls-remote -q -t --refs https://github.com/jgm/pandoc.git | awk '/tags\/[0-9]/{sub("refs/tags/", ""); print $2 }' | awk '!/^$/' | sort -rV | head -n 1)"
          curl -sLo- "https://github.com/jgm/pandoc/releases/latest/download/pandoc-${pandoc_git_tag}-linux-amd64.tar.gz" | tar xzf - --strip-components 2 -C "$(pwd)" --exclude="share"

      - name: Host - Download qbittorrent-nox artifacts ${{ github.event.inputs.distinct_id }}
        uses: actions/download-artifact@v3

      - name: Host - 1.2 artifacts organise for release ${{ github.event.inputs.distinct_id }}
        run: |
          mkdir -p "1.2"
          for files in libtorrent-v1.2-*-qbittorrent-nox; do
              cp -rf ${files}/* "1.2/"
          done

      - name: Host - 2.0 artifacts organise for release ${{ github.event.inputs.distinct_id }}
        run: |
          mkdir -p "2.0"
          for files in libtorrent-v2.0-*-qbittorrent-nox; do
              cp -rf ${files}/* "2.0/"
          done

      - name: Host - merge release-info ${{ github.event.inputs.distinct_id }}
        run: |
          paste -d '\n' 1.2/qt5-release.md 2.0/qt6-release.md | uniq > tmp-release.md
          paste -d '\n' 1.2/qt5-dependency-version.json 2.0/qt6-dependency-version.json | uniq > dependency-version.json
          ./pandoc -f gfm tmp-release.md -t gfm -o release.md

      - name: Host - Bootstrap release tag ${{ github.event.inputs.distinct_id }}
        run: echo "release_tag=$(cat ${{ matrix.libtorrent_version }}/tag.md)" >> $GITHUB_ENV

      - name: Host - Bootstrap release title ${{ github.event.inputs.distinct_id }}
        run: echo "release_title=$(cat ${{ matrix.libtorrent_version }}/title.md)" >> $GITHUB_ENV

      - name: Host- Create release - tag - assets ${{ github.event.inputs.distinct_id }}
        uses: ncipollo/release-action@v1
        with:
          prerelease: "${{ matrix.preview_release }}"
          artifacts: "${{ matrix.libtorrent_version }}/*-qbittorrent-nox,dependency-version.json"
          replacesArtifacts: true
          tag: "${{ env.release_tag }}"
          name: "${{ env.release_title }}"
          bodyFile: "release.md"
          allowUpdates: true
          token: "${{ secrets.GITHUB_TOKEN }}"
