name: zlib-ng+crossbuild+package+release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [zlib-ng]
        os_id: [debian, ubuntu]
        os_version_id: [bullseye, focal, jammy]
        arch: [amd64, armhf, arm64]
        zlib_compat: ["", "-D ZLIB_COMPAT=ON"]
        include:
          - arch: amd64
            CHOST: "x86_64-linux-gnu"
            docker_arch: amd64
            docker_platform: linux/amd64
          - arch: armhf
            CHOST: "arm-linux-gnueabihf"
            docker_arch: arm32v7
            docker_platform: linux/arm/v7
          - arch: arm64
            CHOST: "aarch64-linux-gnu"
            docker_arch: arm64v8
            docker_platform: linux/arm64/v8
          - zlib_compat: ""
            pretty_name: v2
            header_name: ZLIBNG_VERSION
          - zlib_compat: "-D ZLIB_COMPAT=ON"
            pretty_name: v1
            header_name: ZLIB_VERSION
        exclude:
          - os_id: debian
            os_version_id: bionic
          - os_id: debian
            os_version_id: focal
          - os_id: debian
            os_version_id: jammy
          - os_id: ubuntu
            os_version_id: stretch
          - os_id: ubuntu
            os_version_id: buster
          - os_id: ubuntu
            os_version_id: bullseye

    name: ${{ matrix.arch }} ${{ matrix.os_id }}:${{ matrix.os_version_id }} ${{ matrix.name }} ${{ matrix.pretty_name }}
    env:
      opt_dir_name: "opt/local"
      include_dir: "/opt/local/include"
      lib_dir: "/opt/local/lib"
      github_branch: "develop"
      cxx_standard: "17"
      prerelease: true
    outputs:
      draft_id_1: ${{ steps.draft_id_1.outputs.draft_id_1 }}
      draft_id_2: ${{ steps.draft_id_2.outputs.draft_id_2 }}

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Host - update
        run: sudo apt-get update

      - name: Host - upgrade
        run: sudo apt-get -y upgrade

      - name: Host - Install host qemu-static
        run: sudo apt-get install -y qemu binfmt-support qemu-user-static

      - name: Host - Docker multiarch bootstrap
        run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Host - Create Docker template env file
        run: |
          echo "DEBIAN_FRONTEND=noninteractive" > env.custom
          echo "LANG=en_US.UTF-8" >> env.custom
          echo "LANGUAGE=en_US.UTF-8" >> env.custom
          echo "LC_ALL=en_US.UTF-8" >> env.custom
          echo "LC_CTYPE=en_US.UTF-8" >> env.custom
          echo "PATH=/${{ env.opt_dir_name }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> env.custom
          echo "LD_LIBRARY_PATH=/${{ env.opt_dir_name }}/lib:/usr/lib/${{ matrix.CHOST }}:/usr/lib:/usr/local/lib" >> env.custom
          echo "CHOST=${{ matrix.CHOST }}" >> env.custom
          echo "CC=${{ matrix.CHOST }}-gcc" >> env.custom
          echo "AR=${{ matrix.CHOST }}-ar" >> env.custom
          echo "CXX=${{ matrix.CHOST }}-g++" >> env.custom

      - name: Host - Create docker multiarch ${{ matrix.arch }} container
        run: docker run --name multiarch -it -d --env-file env.custom -w /root -v ${{ github.workspace }}:/root ${{ matrix.os_id }}:${{ matrix.os_version_id }}

      - name: Host - Create docker binary test ${{ matrix.arch }} container
        run: docker run --name bintest -it -d --env-file env.custom -w /root --platform ${{ matrix.docker_platform }} -v ${{ github.workspace }}:/root ${{ matrix.docker_arch }}/${{ matrix.os_id }}:${{ matrix.os_version_id }}

      - name: Docker target - Set locale data
        run: |
          docker exec --env-file env.custom multiarch /bin/bash -c 'echo LC_ALL=en_US.UTF-8 >> /etc/environment'
          docker exec --env-file env.custom multiarch /bin/bash -c 'echo en_US.UTF-8 UTF-8 >> /etc/locale.gen'
          docker exec --env-file env.custom multiarch /bin/bash -c 'echo LANG=en_US.UTF-8 > /etc/locale.conf'

      - name: Docker target - fix Ubuntu sources
        if: |
          matrix.os_id == 'ubuntu' && matrix.arch != 'amd64'
        run: |
          docker exec --env-file env.custom -w /etc/apt/ multiarch  bash -c 'echo "deb [arch=${{ matrix.arch }}] http://ports.ubuntu.com/ubuntu-ports ${{ matrix.os_version_id }} main restricted universe multiverse" > sources.list'
          docker exec --env-file env.custom -w /etc/apt/ multiarch  bash -c 'echo "deb [arch=${{ matrix.arch }}] http://ports.ubuntu.com/ubuntu-ports ${{ matrix.os_version_id }}-updates main restricted universe multiverse" >> sources.list'
          docker exec --env-file env.custom -w /etc/apt/ multiarch  bash -c 'echo "deb [arch=${{ matrix.arch }}] http://ports.ubuntu.com/ubuntu-ports ${{ matrix.os_version_id }}-security main restricted universe multiverse" >> sources.list'
          docker exec --env-file env.custom -w /etc/apt/ multiarch  bash -c 'echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ ${{ matrix.os_version_id }} main restricted universe multiverse" >> sources.list'
          docker exec --env-file env.custom -w /etc/apt/ multiarch  bash -c 'echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ ${{ matrix.os_version_id }}-updates main restricted universe multiverse" >> sources.list'
          docker exec --env-file env.custom -w /etc/apt/ multiarch  bash -c 'echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ ${{ matrix.os_version_id }}-backports restricted universe multiverse" >> sources.list'
          docker exec --env-file env.custom -w /etc/apt/ multiarch  bash -c 'echo "deb [arch=amd64] http://security.ubuntu.com/ubuntu/ ${{ matrix.os_version_id }}-security main restricted universe multiverse" >> sources.list'

      - name: Docker target - dpkg configure arch
        run: docker exec --env-file env.custom multiarch dpkg --add-architecture ${{ matrix.arch }}

      - name: Docker target - Run apt-get update
        run: |
          docker exec --env-file env.custom multiarch apt-get update
          docker exec --env-file env.custom bintest apt-get update

      - name: Docker target - fix locales
        run: |
          docker exec --env-file env.custom multiarch apt-get install -y locales
          docker exec --env-file env.custom multiarch locale-gen en_US.UTF-8
          docker exec --env-file env.custom multiarch dpkg-reconfigure locales

      - name: Docker target - Run apt-get upgrade
        run: |
          docker exec --env-file env.custom multiarch apt-get upgrade -y
          docker exec --env-file env.custom bintest apt-get upgrade -y

      - name: Docker target - apt-get install the core build dependencies
        run: |
          docker exec --env-file env.custom multiarch apt-get install -y build-essential curl pkg-config automake libtool git perl python3 python3-dev unzip ccache
          docker exec --env-file env.custom bintest apt-get install -y openssl binutils

      - name: Docker target - apt-get install crossbuild-essential
        if: matrix.arch != 'amd64'
        run: docker exec --env-file env.custom multiarch apt-get install -y crossbuild-essential-${{ matrix.arch }}

      - name: Docker target - apt-get install cross target deps
        run: docker exec --env-file env.custom multiarch apt-get install -y openssl:${{ matrix.arch }} re2c:${{ matrix.arch }} libstdc++-*-dev:${{ matrix.arch }}

      - name: Docker target - bionic - apt-get install gcc-8-base g++-8
        if: matrix.arch == 'amd64' && matrix.os_version_id == 'bionic'
        run: docker exec --env-file env.custom multiarch apt-get install -y gcc-8 g++-8

      - name: Docker target - bionic - apt-get install gcc-8 g++-8 cross
        if: matrix.arch != 'amd64' && matrix.os_version_id == 'bionic'
        run: docker exec --env-file env.custom multiarch apt-get install -y cpp-8-${{ matrix.CHOST }} g++-8-${{ matrix.CHOST }} gcc-8-${{ matrix.CHOST }}

      - name: Docker target - bionic - reconfigure build vars
        if: matrix.os_version_id == 'bionic'
        run: |
          echo "CC=${{ matrix.CHOST }}-gcc-8" >> env.custom
          echo "AR=${{ matrix.CHOST }}-gcc-ar-8" >> env.custom
          echo "CXX=${{ matrix.CHOST }}-g++-8" >> env.custom

      - name: Docker target - cmake and ninja download and install
        run: |
          docker exec --env-file env.custom multiarch curl -sNL "https://github.com/userdocs/cmake-crossbuild/releases/latest/download/${{ matrix.os_id }}-${{ matrix.os_version_id }}-cmake-${{ matrix.arch }}.deb" -o ${{ matrix.os_id }}-${{ matrix.os_version_id }}-cmake-${{ matrix.arch }}.deb
          docker exec --env-file env.custom multiarch dpkg -i ${{ matrix.os_id }}-${{ matrix.os_version_id }}-cmake-${{ matrix.arch }}.deb

      - name: Docker target - Git clone ${{ matrix.name }} develop
        run: docker exec --env-file env.custom -w /root multiarch git clone --single-branch --branch "${{ env.github_branch }}" --shallow-submodules --recurse-submodules --depth 1 https://github.com/zlib-ng/zlib-ng.git /root/${{ matrix.name }}

      - name: Host - Set zlib version to variable
        run: echo "zlib_ng_version=$(cat ${{ matrix.name }}/zlib.h.in | sed -rn 's|#define ${{ matrix.header_name }} "(.*)"|\1|p' | sed 's/\.[^.]*$//')" >> $GITHUB_ENV

      - name: Docker target - Cmake ${{ matrix.name }}
        run: |
          docker exec --env-file env.custom -w /root/${{ matrix.name }} multiarch cmake -Wno-dev -Wno-deprecated -G Ninja -B build \
          ${{ matrix.zlib_compat }} \
          -D CMAKE_VERBOSE_MAKEFILE="ON" \
          -D CMAKE_CXX_STANDARD="${{ env.cxx_standard }}" \
          -D CMAKE_INSTALL_PREFIX="/root/build/${{ env.opt_dir_name }}"

      - name: Docker target - ${{ matrix.name }} - cmake build
        run: docker exec --env-file env.custom -w /root/${{ matrix.name }} multiarch cmake --build build

      - name: Docker target - ${{ matrix.name }} - cmake install
        run: docker exec --env-file env.custom -w /root/${{ matrix.name }} multiarch cmake --install build

      - name: Host - Set zlib release version
        if: matrix.pretty_name == 'v1'
        run: |
          echo "prerelease=false" >> $GITHUB_ENV

      - name: Docker target - Set deb dependencies for ${{ matrix.name }}
        run: echo "zlib-ng-deb-deps=none" >> $GITHUB_ENV

      - name: Docker target - ldconfig - create /etc/ld.so.conf.d/zlib-ng.conf
        run: |
          docker exec --env-file env.custom -w /root/build multiarch mkdir -p etc/ld.so.conf.d
          docker exec --env-file env.custom -w /root/build/etc/ld.so.conf.d multiarch bash -c "echo '/${{ env.opt_dir_name }}/lib' > zlib-ng.conf"

      - name: Host - Create deb packages
        uses: jiro4989/build-deb-action@v2.8.0
        with:
          package: "${{ matrix.name }}"
          package_root: build
          maintainer: userdocs
          compress_type: gzip
          version: "${{ env.zlib_ng_version }}"
          depends: "${{ env.zlib-ng-deb-deps }}"
          arch: "${{ matrix.arch }}"
          desc: "${{ matrix.name }}-${{ env.zlib_ng_version }}-${{ matrix.arch }} for ${{ matrix.os_id }}-${{ matrix.os_version_id }}"

      - name: Host - Remove version from release name and use hyphens
        run: mv -f "${{ matrix.name }}_${{ env.zlib_ng_version }}_${{ matrix.arch }}.deb" "${{ matrix.os_id }}-${{ matrix.os_version_id }}-${{ matrix.name }}-${{ matrix.arch }}.deb"

      - name: Host - "Create release - tag - assets"
        id: release_id
        uses: ncipollo/release-action@v1.11.1
        with:
          prerelease: ${{ env.prerelease }}
          draft: "true"
          commit: ${{ github.ref }}
          artifacts: "${{ matrix.os_id }}-${{ matrix.os_version_id }}-${{ matrix.name }}-${{ matrix.arch }}.deb"
          replacesArtifacts: true
          tag: "${{ env.zlib_ng_version }}"
          name: "${{ matrix.name }} ${{ env.zlib_ng_version }}"
          body: "${{ matrix.name }} built from github master on amd64 arm64 armhf for Debian Stretch Buster Bullseye and Ubuntu Bionic Focal"
          allowUpdates: true
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: process v1
        id: draft_id_1
        if: matrix.pretty_name == 'v1'
        run: echo "draft_id_1=${{ steps.release_id.outputs.id }}" >> $GITHUB_OUTPUT

      - name: process v2
        id: draft_id_2
        if: matrix.pretty_name == 'v2'
        run: echo "draft_id_2=${{ steps.release_id.outputs.id }}" >> $GITHUB_OUTPUT

  publish_draft:
    name: Publish draft release
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.build.outputs.draft_id_1 }}

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.build.outputs.draft_id_2 }}
